[theme]
primaryColor = "#00B050"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0fdf4"
textColor = "#1f2937"

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false